name: cupertino
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/img/ios-11-default-wallpaper.jpg
    - assets/img/AppStoreIcon.png
    - assets/img/BooksIcon.png
    - assets/img/CalendarIcon.png
    - assets/img/CameraIcon.png
    - assets/img/ClockIcon.png
    - assets/img/FacetimeIcon.png
    - assets/img/HealthIcon.png
    - assets/img/ItunesIcon.png
    - assets/img/MailIcon.png
    - assets/img/MapsIcon.png
    - assets/img/MessagesIcon.png
    - assets/img/MusicIcon.png
    - assets/img/NewsIcon.png
    - assets/img/NotesIcon.png
    - assets/img/PhotosIcon.png
    - assets/img/RemindersIcon.png
    - assets/img/SafariIcon.png
    - assets/img/SettingsIcon.png
    - assets/img/StocksIcon.png
    - assets/img/VideosIcon.png
    - assets/img/WalletIcon.png
    - assets/img/WeatherIcon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
